create table public.flyway_schema_history
(
  installed_rank integer                 not null
    constraint flyway_schema_history_pk
      primary key,
  version        varchar(50),
  description    varchar(200)            not null,
  type           varchar(20)             not null,
  script         varchar(1000)           not null,
  checksum       integer,
  installed_by   varchar(100)            not null,
  installed_on   timestamp default now() not null,
  execution_time integer                 not null,
  success        boolean                 not null
);

alter table public.flyway_schema_history
  owner to sa;

create index flyway_schema_history_s_idx
  on public.flyway_schema_history (success);

create table public.o_examples
(
  id                  bigint generated by default as identity
    primary key,
  creation_time       timestamp,
  description         varchar(255),
  identification      varchar(255),
  identification_type integer,
  name                varchar(255),
  days_in_week        integer
);

alter table public.o_examples
  owner to sa;

create table public.assortment
(
  store_id   varchar(255) not null,
  product_id varchar(255) not null,
  primary key (product_id, store_id)
);

alter table public.assortment
  owner to sa;

create table public.category
(
  id   bigint      not null
    primary key,
  name varchar(50) not null
);

alter table public.category
  owner to sa;

create table public.country
(
  id   bigint       not null
    primary key,
  code varchar(2)   not null,
  name varchar(100) not null
);

alter table public.country
  owner to sa;

create table public.course
(
  id   bigint      not null
    primary key,
  name varchar(50) not null
);

alter table public.course
  owner to sa;

create table public.product
(
  id          bigint       not null
    primary key,
  code        varchar(8)   not null,
  name        varchar(50)  not null,
  state       varchar(255) not null,
  category_id bigint       not null
    constraint fk_product_category
      references public.category
);

alter table public.product
  owner to sa;

create table public.comment
(
  id         bigint      not null
    primary key,
  name       varchar(50) not null,
  product_id bigint
    constraint fk_product_comment_id
      references public.product
);

alter table public.comment
  owner to sa;

create table public.store
(
  id   bigint       not null
    primary key,
  code varchar(6)   not null,
  name varchar(100) not null
);

alter table public.store
  owner to sa;

create table public.student
(
  id   bigint      not null
    primary key,
  name varchar(50) not null
);

alter table public.student
  owner to sa;

create table public.enrolment
(
  course_id  bigint    not null
    constraint enrolment_course_id_fk
      references public.course,
  student_id bigint    not null
    constraint enrolment_student_id_fk
      references public.student,
  created_at timestamp not null,
  primary key (course_id, student_id)
);

alter table public.enrolment
  owner to sa;

create table public.tag
(
  id         bigint      not null
    primary key,
  name       varchar(50) not null,
  product_id bigint
    constraint fk_product_tag_id
      references public.product
);

alter table public.tag
  owner to sa;

