apiVersion: v1
description: Helm chart for running alejandro-back-web-dev microservice in Kubernetes
name: alejandro-back-web-dev
version: 1.0.0
keywords:
  - springboot
  - service
  - java
appVersion: 1.0.0
icon: https://www.mercadona.com/estaticos/favicon/favicon-194x194.png
