## IMPORTANT NOTE:
##
## THIS YAML SHOULD CONTAIN THE SHARED CONFIGURATION
## BETWEEN ALL ENVIRONMENTS: DEV, ITG, PRE AND PRO

## Default values for the application.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

springboot-service:
  ## appName and appVersion will be replaced during CI execution
  appName: alejandro-back-web-dev
  appVersion: 1.0.0
  projectName: alejandro

  image:
    ## repository and tag will be replaced during CI execution
    repositoryUrl: docker.artifactory.gcp.mercadona.com
    imagePath: <image>
    tag: <tag>
